### ISSUE TITLE
cask stillage assignment via load_data.pl

### ISSUE THREAD

**Issue by mah11** [tfrayner/beerfestdb#12]
Can load_data.pl be used to assign casks to stillages?

If so, document how to retrieve cask list, with brewery & beer names for human readability, and what to add (i.e. column header and contents) to load stillage assignments.

**Comment by tfrayner** [comment]
This stillage assignment step can be performed using the update_cask_details.pl script (see perldoc `which update_cask_details.pl` for more details). An annotated list of festival cask IDs can be obtained by using dump_to_template.pl with the cask_csv_dump.tt2 template.
