### ISSUE TITLE
json: include approximate bar location

### ISSUE THREAD

**Issue by bertkenward** [tfrayner/beerfestdb#18]
At present brewery bars and KeyKeg beers at Cambridge are stillaged separately from the main run. A user looking at the website or app currently has no indication that the beers are not to be found alphabetically. It would be useful if there were some indication of stillage ordering.

This interacts interestingly with #17 , since products in multiple formats may well be in multiple locations.

**Comment by mah11** [comment]
At present, cellar stillage allocation happens at the cask/container level, and correlates precisely with bar location (i.e. there are cellar stillage entries for "brewery bars" and "keykeg bar").

We have not yet tried to capture ordering of stillages, nor ordering of containers within a stillage (whether either is supported by the db schema or not, we haven't done it in practice).

**Comment by bertkenward** [comment]
What were the various stillage locations called at cbf43? The relationship between name and order could be defined elsewhere.

**Comment by mah11** [comment]
They go by the cellar's often-irreverent internal names: Arctic, Brewery Bars, DMZ, Gay Bar, KeyKegs, Planet Fletch.

For any festival in the db, you can log in and look at the "Casks by Stillage" tab (tho we've used the same names for some years now).

**Comment by bertkenward** [comment]
I think an external thing that knows about the order of the stillages will be fine - the json we serve to the apps doesn't have to be identical to the json beerfestdb sends.

(I'm expecting to add a separate component in between beerfestdb and the public website, mostly because the public website is going to be running on third party code that we don't really want to extend. But that will also provide a useful place for transforming the json in to a public facing version, without adding unnecessary to beerfestdb.)
