### ISSUE TITLE
support AWRS URN

### ISSUE THREAD

**Issue by mah11** [tfrayner/beerfestdb#20]
Add a field to Company for the IDs from the new bit of HMRC bureaucracy. Needs bulk load via load_data.pl, and web interface display, add/update/delete, etc.

Alcohol Wholesalers Registration Scheme URN

**Comment by mah11** [comment]
of the URNs we've seen so far, all have some letters plus 11 digits ... but (wait for it) the 2 dozen or so examples to date already include strings with 3, 4, or 5 letters. <headdesk>

**Comment by bertkenward** [comment]
X[A-Z]AW\d{11} seems to cover most of them doesn't it? Tring is missing the W - I've checked the email from them and I've transcribed it correctly. I guess AW stands for Alcohol Wholesaler...

Maybe this will all make more sense once the .gov.uk website for checking them exists. Hopefully we'll be able to generate URLs for said site directly.
