### ISSUE TITLE
beer cask list for zeroing

### ISSUE THREAD

**Issue by mah11** [tfrayner/beerfestdb#29]
Generate a list of festival cask IDs for existing (i.e. not deleted) casks with product category beer.

Use case: Not having to enter every sodding cask ID manually into the last-day dip data file, when the vast majority are empty.

**Comment by tfrayner** [comment]
This is probably best handled by dumping the output of a (relatively) simple SQL query into a file:

`echo "select cellar_reference from cask_management cm, cask c, festival f where cm.festival_id=f.festival_id and c.cask_management_id=cm.cask_management_id and f.name='43rd Cambridge Beer Festival'" | mysql beerfestdb > output.txt`

**Comment by mah11** [comment]
that worked at cbf45; thanks
